### PR TITLE
add owner loader

### PR DESCRIPTION
**Pull request by zazayaya**
add owner loader decorator

example：
---------------------------------------------
```python
from flask_login import current_user

@casbin_enforcer.owner_loader
def owner():
    return [u.name for u in current_user.roles]
```

### CODE REVIEW

**Comment by zazayaya** [comment]
example：
from flask_login import current_user

@casbin_enforcer.owner_loader
def owner():
    return [u.name for u in current_user.roles]

**Comment by hsluoyz** [comment]
@techoner @yyellowsun please review.

**Comment by jessecooper** [comment]
@zazayaya would it be possible to write some unit tests around this code?

**Comment by zazayaya** [comment]
> @zazayaya would it be possible to write some unit tests around this code?

I have added owner loader unit tests,please review

**Comment by zazayaya** [comment]
> @zazayaya would it be possible to write some unit tests around this code?

i have added owner loader unit tests, please review.

**Comment by jessecooper** [comment]
@zazayaya Thanks for adding the unit tests LGTM.

**Comment by jessecooper** [comment]
I will create and upload a new release to pypi as soon as possible.

**Comment by zazayaya** [comment]
> I will create and upload a new release to pypi as soon as possible.

Thanks!!!

**Pull request merged**
