### PR TITLE
build: set correct package version for download_url to be able to generate a new build

### PR DESCRIPTION
**Pull request by favipcj**
Get the current package version and set it for the download_url  property so the workflow release step can run as expected

### CODE REVIEW

**Comment by ffyuanda** [comment]
@favipcj So what is not expected at this point?

**Comment by favipcj** [comment]
> @favipcj So what is not expected at this point?

There is an error while building the package since this build https://github.com/pycasbin/flask-authz/runs/2590373369?check_suite_focus=true and that is because the version set for the download_url property was not right, so the build was not able to be created successfully, with this change the release step should build the package correctly

**Comment by ffyuanda** [comment]
@favipcj Thanks for bringing up the problem! 

Though this is not the reason that the workflow failed. It is that we should not set the `version` in `setup.py`, and because we did, it fails the `verifyConditions` step in this [plugin](https://www.npmjs.com/package/semantic-release-pypi) at the third bullet point. The `version` keyword should only be set in `setup.cfg`. 

I'll make a PR very soon to straight that up!

**Comment by ffyuanda** [comment]
@favipcj I just realized that there is not `version` set in `setup.py`, while this problem is usually due to this reason, I'm trying to find out the actual cause, which might be solved by your commit.

**Comment by favipcj** [comment]
> @favipcj I just realized that there is no `version` set in `setup.py`, while this problem is usually due to this reason, I'm trying to find out the actual cause, which might be solved by your commit.

@ffyuanda, the issue is related to the word `version` that was used in the `setup` function on the `download_url` arg, I was able to reproduce this issue in another project and I tried some other approaches to have the correct version for the `download_url` arg, but I ended up choosing this one as the other approaches like moving download_url to setup.cfg were not working fine when getting the current package version.

**Review by Zxilly — APPROVED** [review]
lgtm

**Review by jessecooper — APPROVED** [review]

**Review by techoner — APPROVED** [review]

**Comment by favipcj** [comment]
Guys, it seems that the last version of `casbin_sqlalchemy_adapter==0.4.0` is breaking the tests of flask_authz. 

I think this https://github.com/pycasbin/sqlalchemy-adapter/commit/84ed6eea02a3200807f01c194f83a058bac038ac#diff-8b2ed1334730ff3be23f40e56f02a69520705881cb6764665f9a446aa11799c0R46 should be:
`class Adapter(persist.Adapter, persist.adapters.update_adapter.UpdateAdapter`. I can open a PR to fix that if needed

**Pull request merged**
